[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/Adafruit ILI9341 @ ^1.6.0  ; <--- TAMBAHAN BARU
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
    adafruit/RTClib @ ^2.1.1
    bblanchon/ArduinoJson @ ^6.21.3